service:
  extensions:
    - jaeger_storage
    - jaeger_query
    - healthcheckv2
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - jaeger_storage_exporter
  telemetry:
    metrics:
      level: none

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: "0.0.0.0:13133"

  jaeger_storage:
    backends:
      databus_traces:
        memory:
          max_traces: 200000

  jaeger_query:
    storage:
      traces: databus_traces
    http:
      endpoint: "0.0.0.0:16686"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4319"

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  jaeger_storage_exporter:
    trace_storage: databus_traces
